version: "3.8"

services:
  web:
    container_name: accounts_management_api
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .docker.env
    ports:
      - "8080:8080"
    volumes:
      - .:/code
